name: run sendMail
on:
  push:

jobs:
  build:
    name: run python build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run python
      run: |
        python3 sendMail.py